vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    illustration:
      uri_prefix: /media
      upload_destination: '%kernel.project_dir%/public/media'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    city_images:
      uri_prefix: /media/cities
      upload_destination: '%kernel.project_dir%/public/media/cities'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
